name: Build, Test and Deploy to Prod

# Trigger the workflow when changes are pushed to the main branch
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Cache dependencies to speed up build times
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            app-service/cargo
            app-service/target/
            auth-service/cargo
            auth-service/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      # Install Rust
      - name: Install Rust
        run: rustup update stable && rustup default stable

      # Build and test app-service code
      - name: Build and test app-service code
        working-directory: ./app-service
        run: |
          cargo build --verbose
          cargo test --verbose

      # Build and test auth-service code
      - name: Build and test auth-service code
        working-directory: ./auth-service
        run: |
          export JWT_SECRET=secret  # Add this line
          cargo build --verbose
          cargo test --verbose

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Docker images
      - name: Build and push Docker images
        uses: docker/bake-action@v2.3.0
        with:
          files: |
            compose.yml
            compose.override.yml
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max

  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Install sshpass
      - name: Install sshpass
        run: sudo apt-get install sshpass

      # Copy compose.yml to droplet
      - name: Copy compose.yml to droplet
        run: sshpass -p ${{ secrets.DROPLET_PASSWORD }} scp -o StrictHostKeyChecking=no compose.yml root@${{ vars.DROPLET_IP }}:/~

      # Deploy
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.DROPLET_IP }}
          username: root
          password: ${{ secrets.DROPLET_PASSWORD }}
          script: |
            cd ~
            export AUTH_SERVICE_IP=${{ vars.DROPLET_IP }}
            export JWT_SECRET=${{ secrets.JWT_SECRET }}  # Add this line
            docker compose down
            docker compose pull
            docker compose up -d